import Foundation

/// Raw teaching material for one node. The `Composer` turns it into a varied lesson depending on the node kind.
/// Hand-written for flagship courses, generated by the on-device model or templates for everything else.
struct KnowledgeSeed: Sendable {
    struct Question: Sendable {
        var prompt: String
        var options: [String]
        var correct: Int
        var why: String?
    }

    struct Blank: Sendable {
        var sentence: String
        var options: [String]
        var correct: Int
        var why: String?
    }

    var intro: String = ""
    var cards: [StoryCard] = []
    var script: [String] = []
    var flashcards: [Flashcard] = []
    var questions: [Question] = []
    var statements: [Statement] = []
    var pairs: [Pair] = []
    var sequencePrompt: String? = nil
    var sequence: [String] = []
    var blanks: [Blank] = []
    var scenario: LessonModule? = nil
    /// Hands-on modules (timer, camera, code lab, mission, teach-back, roleplay, live call…).
    var practice: [LessonModule] = []
    var takeaways: [String] = []
}

// Terse builders for seed literals: `.q(…)`, `.b(…)`, `.s(…)`, `.p(…)`, `.f(…)`.
extension KnowledgeSeed.Question {
    static func q(_ prompt: String, _ options: [String], _ correct: Int, _ why: String? = nil) -> Self {
        .init(prompt: prompt, options: options, correct: correct, why: why)
    }
}
extension KnowledgeSeed.Blank {
    static func b(_ sentence: String, _ options: [String], _ correct: Int, _ why: String? = nil) -> Self {
        .init(sentence: sentence, options: options, correct: correct, why: why)
    }
}
extension Statement {
    static func s(_ text: String, _ isTrue: Bool, _ why: String? = nil) -> Statement { Statement(text: text, isTrue: isTrue, why: why) }
}
extension Pair {
    static func p(_ left: String, _ right: String) -> Pair { Pair(left: left, right: right) }
}
extension Flashcard {
    static func f(_ front: String, _ back: String) -> Flashcard { Flashcard(front: front, back: back) }
}

/// Arranges seeds into lessons with a shape that fits each node kind:
/// teach first, alternate practice types, hands-on where it fits, end on a recap.
enum Composer {
    static func compose(title: String, kind: NodeKind, seed: KnowledgeSeed, earlier: [KnowledgeSeed] = [],
                        nodeID: UUID, author: String = "ilo · offline") -> Lesson {
        var rng = SeededRNG(seed: stableHash(title))
        let pool = Pool(current: seed, earlier: earlier, rng: &rng)
        var modules: [LessonModule?]

        switch kind {
        case .lesson:
            modules = [pool.teach, pool.mcq(0), pool.match, pool.blank(0), pool.practice(0), pool.trueFalse, pool.mcq(1), pool.recap]
        case .story:
            modules = [pool.teach, pool.scenario ?? pool.mcq(0), pool.reorder, pool.mcq(1), pool.practice(0) ?? pool.trueFalse,
                       pool.blank(0), pool.recap]
        case .practice:
            modules = [pool.teach, pool.practice(0), pool.mcq(0), pool.practice(1), pool.blank(0), pool.practice(2), pool.match, pool.recap]
        case .mission:
            let mission = seed.practice.first { $0.type == .mission }
            let others = seed.practice.filter { $0.type != .mission }
            modules = [pool.teach, pool.reorder ?? pool.mcq(0), pool.mcq(1), others.first, mission, pool.reflection(title: title), pool.recap]
        case .review:
            modules = [pool.reviewFlashcards, pool.reviewSpeed, pool.reviewMatch, pool.reviewMCQ(0), pool.reviewBlank,
                       pool.reviewMCQ(1), pool.reviewTrueFalse]
        case .boss:
            modules = [pool.reviewSpeed, pool.reviewMCQ(0), pool.reviewMatch, pool.reviewReorder ?? pool.reviewMCQ(1), pool.reviewBlank,
                       pool.scenario ?? pool.reviewScenario ?? pool.reviewMCQ(2), pool.teachBack(title: title), pool.reviewMCQ(3), pool.finalSpeed]
        case .call:
            let call = seed.practice.first { $0.type == .liveCall || $0.type == .roleplay }
            modules = [pool.teach, pool.mcq(0), call ?? pool.defaultCall(title: title), pool.trueFalse, pool.match, pool.recap]
        case .chest:
            modules = [pool.recap]
        }

        var list = modules.compactMap { $0 }.filter(\.isValid)
        // Top up thin lessons with whatever else the pool has.
        var extra = 2
        while list.count < 6, let filler = pool.filler(excluding: list, index: extra) {
            list.insert(filler, at: max(list.count - 1, 1))
            extra += 1
        }
        list = spreadOut(list)
        if list.count > 10 { list = Array(list.prefix(9)) + [list[list.count - 1]] }

        let takeaways = seed.takeaways.isEmpty ? earlier.last?.takeaways ?? [] : seed.takeaways
        return Lesson(nodeID: nodeID, title: title,
                      intro: seed.intro.isEmpty ? defaultIntro(kind, title) : seed.intro,
                      modules: list.map { var m = $0; m.id = UUID(); return m },
                      takeaways: Array(takeaways.prefix(3)), generatedBy: author)
    }

    /// Moves modules so the same type never appears twice in a row (keeps the first and last in place).
    static func spreadOut(_ input: [LessonModule]) -> [LessonModule] {
        var list = input
        guard list.count > 2 else { return list }
        for i in 1..<(list.count - 1) where list[i].type == list[i - 1].type {
            if let j = list.indices.dropFirst(i + 1).dropLast().first(where: { list[$0].type != list[i].type && list[$0].type != list[i - 1].type }) {
                list.swapAt(i, j)
            }
        }
        return list
    }

    static func defaultIntro(_ kind: NodeKind, _ title: String) -> String {
        switch kind {
        case .lesson: "New idea today: \(title). Five minutes, zero stress."
        case .story: "Story time — watch how \(title.lowercased()) plays out in real life."
        case .practice: "Hands on! Today we practise \(title.lowercased()) for real."
        case .mission: "Mission day. Let's prep, then you go do it."
        case .review: "Quick review — let's make yesterday's ideas stick."
        case .boss: "Boss battle! Everything from this unit, a little faster."
        case .call: "Warm up, then we talk it through out loud."
        case .chest: "Treasure!"
        }
    }

    static func stableHash(_ text: String) -> UInt32 {
        var hash: UInt32 = 2_166_136_261
        for byte in text.utf8 { hash = (hash ^ UInt32(byte)) &* 16_777_619 }
        return hash
    }
}

/// Everything the composer can pull from, pre-shuffled deterministically.
private final class Pool {
    let current: KnowledgeSeed
    let earlier: [KnowledgeSeed]
    private let mixedQuestions: [KnowledgeSeed.Question]
    private let mixedStatements: [Statement]
    private let mixedPairs: [Pair]
    private let mixedBlanks: [KnowledgeSeed.Blank]
    private let mixedFlashcards: [Flashcard]

    init(current: KnowledgeSeed, earlier: [KnowledgeSeed], rng: inout SeededRNG) {
        self.current = current
        self.earlier = earlier
        let all = Array(earlier.suffix(6)) + [current]
        mixedQuestions = all.flatMap(\.questions).shuffled(using: &rng)
        mixedStatements = all.flatMap(\.statements).shuffled(using: &rng)
        mixedPairs = all.flatMap(\.pairs).shuffled(using: &rng)
        mixedBlanks = all.flatMap(\.blanks).shuffled(using: &rng)
        mixedFlashcards = (all.flatMap(\.flashcards) + all.flatMap(\.pairs).map { Flashcard(front: $0.left, back: $0.right) }).shuffled(using: &rng)
    }

    // MARK: Current node

    var teach: LessonModule? {
        if !current.cards.isEmpty { return .story(nil, current.cards) }
        if !current.script.isEmpty { return .listen("Listen", current.script) }
        return nil
    }

    func mcq(_ i: Int) -> LessonModule? {
        guard i < current.questions.count else { return nil }
        let q = current.questions[i]
        return .mcq(q.prompt, q.options, q.correct, why: q.why)
    }

    func blank(_ i: Int) -> LessonModule? {
        guard i < current.blanks.count else { return nil }
        let b = current.blanks[i]
        return .blank(b.sentence, b.options, b.correct, why: b.why)
    }

    var match: LessonModule? {
        guard current.pairs.count >= 3 else { return nil }
        return .match("Match each one", current.pairs.prefix(5).map { ($0.left, $0.right) })
    }

    var trueFalse: LessonModule? {
        guard current.statements.count >= 2 else { return nil }
        return LessonModule(type: .trueFalse, prompt: "True or false?", statements: Array(current.statements.prefix(4)))
    }

    var reorder: LessonModule? {
        guard current.sequence.count >= 3 else { return nil }
        return .order(current.sequencePrompt ?? "Put these in the right order", current.sequence)
    }

    var scenario: LessonModule? { current.scenario }

    func practice(_ i: Int) -> LessonModule? { i < current.practice.count ? current.practice[i] : nil }

    var recap: LessonModule? {
        if current.flashcards.count >= 2 { return LessonModule(type: .flashcards, title: "Recap", flashcards: Array(current.flashcards.prefix(5))) }
        if current.statements.count >= 4 {
            return LessonModule(type: .speedRound, title: "Recap", prompt: "Quick-fire recap!", statements: Array(current.statements.suffix(5)), seconds: 30)
        }
        if current.pairs.count >= 2 {
            return LessonModule(type: .flashcards, title: "Recap", flashcards: current.pairs.prefix(5).map { Flashcard(front: $0.left, back: $0.right) })
        }
        if !current.takeaways.isEmpty {
            return .story("Recap", current.takeaways.enumerated().map { storyCard("Key idea \($0.offset + 1)", $0.element, "checkmark.seal.fill", .proud) })
        }
        return nil
    }

    func reflection(title: String) -> LessonModule {
        .free("How did “\(title)” go? What surprised you, and what will you do differently next time?",
              rubric: ["Describes what they actually did", "Names one thing that was hard or surprising", "Names one concrete next step"],
              sample: "I did it in the kitchen for two minutes. Keeping the rhythm was harder than I expected, so next time I'll count out loud from the start.",
              title: "Debrief")
    }

    func teachBack(title: String) -> LessonModule? {
        if let t = current.practice.first(where: { $0.type == .teachBack }) { return t }
        let points = Array((current.takeaways.isEmpty ? earlier.flatMap(\.takeaways) : current.takeaways).prefix(3))
        guard !points.isEmpty else { return nil }
        return .teach("Teach ilo the most important idea from “\(title)” in your own words, with one example.",
                      rubric: points, sample: points.joined(separator: " "))
    }

    func defaultCall(title: String) -> LessonModule {
        .call("ilo, your friendly coach", goal: "Explain \(title.lowercased()) out loud and answer one follow-up question",
              opening: "Hey! Tell me in your own words: what's the big idea behind \(title.lowercased())?", turns: 4)
    }

    // MARK: Review / boss (mix of earlier nodes)

    var reviewFlashcards: LessonModule? {
        guard mixedFlashcards.count >= 2 else { return nil }
        return LessonModule(type: .flashcards, title: "Warm-up", flashcards: Array(mixedFlashcards.prefix(5)))
    }

    var reviewSpeed: LessonModule? {
        guard mixedStatements.count >= 3 else { return nil }
        return LessonModule(type: .speedRound, title: "Speed round", prompt: "True or false — fast!", statements: Array(mixedStatements.prefix(6)), seconds: 35)
    }

    var finalSpeed: LessonModule? {
        let rest = Array(mixedStatements.dropFirst(6).prefix(6))
        let statements = rest.count >= 3 ? rest : Array(mixedStatements.suffix(6))
        guard statements.count >= 3 else { return recap }
        return LessonModule(type: .speedRound, title: "Final round", prompt: "Last push — beat the clock!", statements: statements, seconds: 30)
    }

    var reviewTrueFalse: LessonModule? {
        let statements = Array(mixedStatements.dropFirst(6).prefix(4))
        guard statements.count >= 2 else { return recap }
        return LessonModule(type: .trueFalse, title: "Recap", prompt: "True or false?", statements: statements)
    }

    var reviewMatch: LessonModule? {
        guard mixedPairs.count >= 3 else { return nil }
        return .match("Match what you've learned", mixedPairs.prefix(5).map { ($0.left, $0.right) })
    }

    func reviewMCQ(_ i: Int) -> LessonModule? {
        guard i < mixedQuestions.count else { return nil }
        let q = mixedQuestions[i]
        return .mcq(q.prompt, q.options, q.correct, why: q.why)
    }

    var reviewReorder: LessonModule? {
        guard let seed = earlier.reversed().first(where: { $0.sequence.count >= 3 }) else { return nil }
        return .order(seed.sequencePrompt ?? "Put these in the right order", seed.sequence)
    }

    var reviewScenario: LessonModule? { earlier.reversed().compactMap(\.scenario).first }

    var reviewBlank: LessonModule? {
        guard let b = mixedBlanks.first else { return nil }
        return .blank(b.sentence, b.options, b.correct, why: b.why)
    }

    /// Anything not used yet, to pad short lessons.
    func filler(excluding used: [LessonModule], index: Int) -> LessonModule? {
        let usedPrompts = Set(used.compactMap(\.prompt))
        let candidates: [LessonModule?] = [
            mcq(index), blank(index - 1), reviewMCQ(index + 2), trueFalse, match, reorder, reviewMatch, reviewSpeed, reviewFlashcards,
        ]
        return candidates.compactMap { $0 }.first { module in
            module.isValid && !(module.prompt.map(usedPrompts.contains) ?? false) && !used.contains { $0.type == module.type && $0.prompt == module.prompt }
        }
    }
}

/// Deterministic RNG (SplitMix64) usable with `shuffled(using:)`.
struct SeededRNG: RandomNumberGenerator {
    private var state: UInt64
    init(seed: UInt32) { state = UInt64(seed) &* 0x9E37_79B9_7F4A_7C15 | 1 }
    mutating func next() -> UInt64 {
        state &+= 0x9E37_79B9_7F4A_7C15
        var z = state
        z = (z ^ (z >> 30)) &* 0xBF58_476D_1CE4_E5B9
        z = (z ^ (z >> 27)) &* 0x94D0_49BB_1331_11EB
        return z ^ (z >> 31)
    }
}
